apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gosentinel.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  postgres_dsn: {{ .Values.postgres.dsn | quote }}
  jwt_secret: {{ .Values.api.jwtSecret | quote }}
  slack_webhook: {{ .Values.alerting.slackWebhook | quote }}
  pagerduty_key: {{ .Values.alerting.pagerdutyKey | quote }}
