global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: http://victoriametrics:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      max_shards: 200
      capacity: 2500

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: otel-collector
    static_configs:
      - targets: [otel-collector:8888]

  - job_name: order-service
    static_configs:
      - targets: [order-service:8081]
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: order-service

  - job_name: inventory-service
    static_configs:
      - targets: [inventory-service:8082]
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: inventory-service

  - job_name: payment-service
    static_configs:
      - targets: [payment-service:8083]
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: payment-service

  - job_name: gosentinel-pipeline
    static_configs:
      - targets: [gosentinel-pipeline:9090]

  - job_name: gosentinel-api
    static_configs:
      - targets: [gosentinel-api:8080]
